# Configurazione Datasource tramite Variabili d'Ambiente
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jarfin_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password_segreta}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update} 
spring.jpa.show-sql=${SHOW_SQL:true}